name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: pod install
      run: pod install
    - name: Build
      run: xcodebuild -workspace Pock.xcworkspace -scheme Pock
